apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: medlemskap-sykepenger-listener
  namespace: medlemskap
  labels:
    team: medlemskap
spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: sykmedlemskap
            envVarPrefix: DB
            diskAutoresize: true
            tier: db-g1-small
  azure:
    application:
      enabled: true
  image: {{image}}
  liveness:
    path: "/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  ingresses:
    - https://medlemskap-vurdering-sykepenger.intern.dev.nav.no
  readiness:
    path: "/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  protected: true
  accessPolicy:
    inbound:
      rules:
        - application: sparkel-medlemskap
          namespace: tbd
          cluster: dev-fss
        - application: sykepengesoknad-backend
          namespace: flex
        - application: sykepengesoknad-arkivering-oppgave
          namespace: flex
    outbound:
      rules:
        - application: medlemskap-saga
        - application: medlemskap-oppslag
      external:
        - host: api-gw-q1.oera.no
        - host: api-gw-q2.oera.no
        - host: saf.dev-fss-pub.nais.io
        - host: login.microsoftonline.com
  env:
    - name: AZURE_TENANT
      value: 966ac572-f5b7-4bbe-aa88-c76419c0f851
    - name: AZURE_AUTHORITY_ENDPOINT
      value: https://login.microsoftonline.com
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://api-gw-q1.oera.no/sts/SecurityTokenServiceProvider/
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://api-gw-q1.oera.no/security-token-service
    - name: MEDL_OPPSLAG_BASE_URL
      value: http://medlemskap-oppslag.medlemskap.svc.cluster.local
    - name: MEDL_OPPSLAG_CLIENT_ID
      value: 2719da58-489e-4185-9ee6-74b7e93763d2
    - name: MEDL_SAGA_CLIENT_ID
      value: 39f402c0-7373-49e3-9e64-9669181f78d4
    - name: MEDL_SAGA_BASE_URL
      value: http://medlemskap-saga.medlemskap.svc.cluster.local
    - name: KAFKA_ENABLED
      value: Nei
    - name: BRUKERSPORSMAAL_ENABLED
      value: Ja