apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: medlemskap-sykepenger-listener
  namespace: medlemskap
  labels:
    team: medlemskap
spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: sykmedlemskap
            envVarPrefix: DB
            diskAutoresize: true
  azure:
    application:
      enabled: true
  image: {{image}}
  liveness:
    path: "/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  ingresses:
    - https://medlemskap-vurdering-sykepenger.intern.nav.no
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  protected: true
  accessPolicy:
    inbound:
      rules:
        - application: sparkel-medlemskap
          namespace: tbd
          cluster: prod-fss
        - application: sykepengesoknad-backend
          namespace: flex
        - application: sykepengesoknad-arkivering-oppgave
          namespace: flex
    outbound:
      rules:
        - application: medlemskap-oppslag
        - application: medlemskap-saga
      external:
        - host: api-gw.oera.no
        - host: login.microsoftonline.com
  env:
    - name: AZURE_TENANT
      value: 966ac572-f5b7-4bbe-aa88-c76419c0f851
    - name: AZURE_AUTHORITY_ENDPOINT
      value: https://login.microsoftonline.com
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://api-gw.oera.no/sts/SecurityTokenServiceProvider/
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://api-gw.oera.no/security-token-service
    - name: MEDL_OPPSLAG_BASE_URL
      value: http://medlemskap-oppslag.medlemskap.svc.cluster.local
    - name: MEDL_OPPSLAG_CLIENT_ID
      value: 23600ac9-019c-445d-87a4-2df4996e6f63
    - name: MEDL_SAGA_CLIENT_ID
      value: 46a1a151-80bf-4e9a-9c06-3ed10c2bb2f2
    - name: MEDL_SAGA_BASE_URL
      value: http://medlemskap-saga.medlemskap.svc.cluster.local
    - name: KAFKA_ENABLED
      value: Nei
    - name: BRUKERSPORSMAAL_ENABLED
      value: Ja
