name: build
permissions:
  contents: "read"
on:
  pull_request:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
      packages: "read"
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: test and build
        uses: actions/setup-java@v4.9.1
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: true
      - run: ./gradlew test shadowJar
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: medlemskap # required
      - name: Post failures to Slack
        if: failure()
        run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"$CHANNEL\", \"text\": \"$MESSAGE\", \"icon_emoji\": \":ghost:\"}" $WEBHOOK_URL
        env:
          MESSAGE: "Bygg feilet"
          CHANNEL: "#lovme-teknisk"
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  deploypreprod:
    name: Deploy to Preprod
    needs: build_and_push
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v6
      - uses: nais/setup@v1
        with:
          team: medlemskap
      - name: Deploy to dev-gcp
        run: |
          nais apply .nais/topics/medlemskapsvurderinger-dev.yaml --environment dev-gcp
          nais apply .nais/dev.yaml \
            --environment dev-gcp \
            --set spec.image="${{ needs.build_and_push.outputs.image }}" \
            --wait